package errorutil

type errcode string
type modulecode string

const (
	user_module   modulecode = "01"
	device_module modulecode = "02"
)

const (
	CreateUserFailed                = "001"
	SelectAllUserFailed             = "002"
	DeleteUserFailed                = "003"
	StrconvFailed                   = "004"
	SelectUserByIDFailed            = "005"
	UpdateUserFailed                = "006"
	GetAllBookFiled                 = "007"
	CreateBookFailed                = "008"
	JsonTransformFailed             = "009"
	SelectAllBookFailed             = "010"
	DeleteBookFailed                = "011"
	SelectBookByIDFailed            = "012"
	UpdateBookFailed                = "013"
	SelectUsernumberFailed          = "014"
	UsernameNotRight                = "015"
	BorrowAndUpdateBookStatusFailed = "016"
	BookAlreadyBorrowed             = "017"
	AddBorrowInfoFailed             = "018"
	SelectBorrowByNumberFailed      = "019"
	BookAlreadyBack                 = "020"
	BackUpdateBookStatusFailed      = "021"
	UpdateBorrowInformationFailed   = "022"
	SelectBookRecordFailed          = "023"
	BooknumberIsZero                = "024"

	LoginUsernameFailed                = "010"
	LoginPasswordFailed                = "011"
	LoginFailed                        = "012"
	CreateTokenFailed                  = "013"
	CreateCompanyFailed                = "015"
	UpdateCompanyFailed                = "016"
	DeleteCompanyFailed                = "017"
	SelectAllCompanyFailed             = "018"
	SelectCompanyByIDFailed            = "019"
	CreateManagerAlreadyExist          = "020"
	CreateManagerFailed                = "021"
	SelectAllManagerFailed             = "022"
	SelectManagerByIDFailed            = "023"
	UpdateManagerFailed                = "024"
	DeleteManagerFailed                = "025"
	CreateGroupAlreadyExist            = "026"
	CreateGroupFailed                  = "027"
	SelectAllGroupFailed               = "028"
	SelectGroupByIDFailed              = "029"
	UpdateGroupFailed                  = "030"
	DeleteGroupFailed                  = "031"
	CreateDeviceAlreadyExist           = "032"
	CreateDeviceFailed                 = "033"
	SelectDeviceByIDFailed             = "034"
	UpdateDeviceFailed                 = "035"
	NewUUidFailed                      = "036"
	SelectAllDeviceFailed              = "037"
	DeleteDeviceFailed                 = "038"
	SelectDiagdataFilterTimeIsNotDigit = "039"
	UpdateSoftwareFailed               = "040"
	SystemIsDisconected                = "041"
	RequestConfigFailed                = "042"
	ParseConfigFailed                  = "043"
	UpdateUserAlreadyExist             = "044"
	UpdateCompanyAlreadyExist          = "045"
	UpdateDeviceAlreadyExist           = "046"
	LoginFailedWithoutCompany          = "047"
)
